CookBook/CookBook/Models/Recipe.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CookBook.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recipe
    {
        public Recipe()
        {
            this.RecipeIngredients = new HashSet<RecipeIngredient>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int PrepTime { get; set; }
        public int CookTime { get; set; }
        public int NumberServ { get; set; }
        public string Steps { get; set; }
        public string RecipeType { get; set; }
    
        public virtual ICollection<RecipeIngredient> RecipeIngredients { get; set; }
    }
}

CookBook/CookBook/Controllers/RecipeController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CookBook.Models;

namespace CookBook.Controllers
{
    public class RecipeController : Controller
    {
        private RecipeEntities db = new RecipeEntities();

        // GET: Recipe
        public ViewResult Index(string searchString)
        {
            var recipes = from r in db.Recipes select r;
            if (!String.IsNullOrEmpty(searchString))
            {
                recipes = recipes.Where(r => r.RecipeType.ToUpper().Contains(searchString.ToUpper()));
            }
            return View(recipes.ToList());
        }

        // GET: Recipe/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Recipe recipe = db.Recipes.Find(id);
            if (recipe == null)
            {
                return HttpNotFound();
            }
            return View(recipe);
        }

        // GET: Recipe/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Recipe/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name,PrepTime,CookTime,NumberServ,Steps,RecipeType")] Recipe recipe)
        {
            if (ModelState.IsValid)
            {
                db.Recipes.Add(recipe);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(recipe);
        }

        // GET: Recipe/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Recipe recipe = db.Recipes.Find(id);
            if (recipe == null)
            {
                return HttpNotFound();
            }
            return View(recipe);
        }

        // POST: Recipe/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name,PrepTime,CookTime,NumberServ,Steps,RecipeType")] Recipe recipe)
        {
            if (ModelState.IsValid)
            {
                db.Entry(recipe).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(recipe);
        }

        // GET: Recipe/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Recipe recipe = db.Recipes.Find(id);
            if (recipe == null)
            {
                return HttpNotFound();
            }
            return View(recipe);
        }

        // POST: Recipe/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Recipe recipe = db.Recipes.Find(id);
            db.Recipes.Remove(recipe);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

CookBook/CookBook/Controllers/RecipeIngredientController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CookBook.Models;

namespace CookBook.Controllers
{
    public class RecipeIngredientController : Controller
    {
        private RecipeEntities db = new RecipeEntities();

        // GET: RecipeIngredient
        public ActionResult Index()
        {
            var recipeIngredients = db.RecipeIngredients.Include(r => r.Ingredient).Include(r => r.Recipe);
            return View(recipeIngredients.ToList());
        }

        // GET: RecipeIngredient/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            RecipeIngredient recipeIngredient = db.RecipeIngredients.Find(id);
            if (recipeIngredient == null)
            {
                return HttpNotFound();
            }
            return View(recipeIngredient);
        }

        // GET: RecipeIngredient/Create
        public ActionResult Create()
        {
            ViewBag.IngredientId = new SelectList(db.Ingredients, "Id", "IngredientName");
            ViewBag.RecipeId = new SelectList(db.Recipes, "Id", "Name");
            return View();
        }

        // POST: RecipeIngredient/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,RecipeId,IngredientId,Amount,AmountSize")] RecipeIngredient recipeIngredient)
        {
            if (ModelState.IsValid)
            {
                db.RecipeIngredients.Add(recipeIngredient);
                db.SaveChanges();
                return RedirectToAction("Index","Recipe");
            }

            ViewBag.IngredientId = new SelectList(db.Ingredients, "Id", "IngredientName", recipeIngredient.IngredientId);
            ViewBag.RecipeId = new SelectList(db.Recipes, "Id", "Name", recipeIngredient.RecipeId);
            return View(recipeIngredient);
        }

        // GET: RecipeIngredient/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            RecipeIngredient recipeIngredient = db.RecipeIngredients.Find(id);
            if (recipeIngredient == null)
            {
                return HttpNotFound();
            }
            ViewBag.IngredientId = new SelectList(db.Ingredients, "Id", "IngredientName", recipeIngredient.IngredientId);
            ViewBag.RecipeId = new SelectList(db.Recipes, "Id", "Name", recipeIngredient.RecipeId);
            return View(recipeIngredient);
        }

        // POST: RecipeIngredient/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,RecipeId,IngredientId,Amount,AmountSize")] RecipeIngredient recipeIngredient)
        {
            if (ModelState.IsValid)
            {
                db.Entry(recipeIngredient).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.IngredientId = new SelectList(db.Ingredients, "Id", "IngredientName", recipeIngredient.IngredientId);
            ViewBag.RecipeId = new SelectList(db.Recipes, "Id", "Name", recipeIngredient.RecipeId);
            return View(recipeIngredient);
        }

        // GET: RecipeIngredient/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            RecipeIngredient recipeIngredient = db.RecipeIngredients.Find(id);
            if (recipeIngredient == null)
            {
                return HttpNotFound();
            }
            return View(recipeIngredient);
        }

        // POST: RecipeIngredient/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            RecipeIngredient recipeIngredient = db.RecipeIngredients.Find(id);
            db.RecipeIngredients.Remove(recipeIngredient);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

CookBook/CookBook/Views/Recipe/Create.cshtml
@model CookBook.Models.Recipe
@{
    ViewBag.Title = "Create";
}
<body style="background-image:url(http://www.presentationmagazine.com/images3/background-design-orange1024.jpg)">
<h2>Create</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4 style="font-size:xx-large">Recipe</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PrepTime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PrepTime, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PrepTime, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CookTime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CookTime, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CookTime, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NumberServ, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NumberServ, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NumberServ, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Steps, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @*   @Html.EditorFor(model => model.Steps, new { htmlAttributes = new { @class = "form-control" } })*@
                @*@Html.TextAreaFor(model => model.Steps, new { htmlAttributes = new { @class = "form-control", style="width: 100px;, multiple;, rows='4';, cols='50';" }  })*@
                @Html.TextAreaFor(model => model.Steps, new { htmlAttributes = new { @class = "form-control", cols = "1000", rows = "1000", wrap = "virtual" } })

                @Html.ValidationMessageFor(model => model.Steps, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RecipeType, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RecipeType, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RecipeType, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}
</body>

CookBook/CookBook/Views/Recipe/Delete.cshtml
@model CookBook.Models.Recipe

@{
    ViewBag.Title = "Delete";
}
<body style="background-image:url(http://www.presentationmagazine.com/images3/background-design-orange1024.jpg)">
<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4 style="font-size:x-large">Recipe</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt style="font-size:medium" >
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt style="font-size:medium" >
            @Html.DisplayNameFor(model => model.PrepTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PrepTime)
        </dd>

        <dt style="font-size:medium">
            @Html.DisplayNameFor(model => model.CookTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CookTime)
        </dd>

        <dt style="font-size:medium">
            @Html.DisplayNameFor(model => model.NumberServ)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NumberServ)
        </dd>

        <dt style="font-size:medium">
            @Html.DisplayNameFor(model => model.Steps)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Steps)
        </dd>

        <dt style="font-size:medium">
            @Html.DisplayNameFor(model => model.RecipeType)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RecipeType)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>
    </body>

CookBook/CookBook/Views/Recipe/Details.cshtml
@model CookBook.Models.Recipe

@{
    ViewBag.Title = "Details";
}
<body style="background-image:url(http://www.presentationmagazine.com/images3/background-design-orange1024.jpg)">
<h2>Details</h2>

<div>
    <h4 style="font-size:xx-large">Recipe</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt style="font-size:medium">
            @Html.DisplayNameFor(model => model.RecipeType)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RecipeType)
        </dd>
        <dt style="font-size:medium">
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt style="font-size:medium">
            @Html.DisplayNameFor(model => model.PrepTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PrepTime)
        </dd>

        <dt style="font-size:medium">
            @Html.DisplayNameFor(model => model.CookTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CookTime)
        </dd>

        <dt style="font-size:medium">
            @Html.DisplayNameFor(model => model.NumberServ)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NumberServ)
        </dd>

        <dt style="font-size:medium">
            @Html.DisplayNameFor(model => model.RecipeIngredients)
        </dt>
        <dd>
            <table class="table">
                <tr>
                    <th>Ingredient Name</th>
                    <th>Amount</th>
                    <th>Amount Size</th>
                </tr>
                @foreach (var item in Model.RecipeIngredients)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Ingredient.IngredientName)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Amount)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.AmountSize)
                        </td>
                    </tr>
                }
            </table>
        </dd>

        <dt style="font-size:medium">
            @Html.DisplayNameFor(model => model.Steps)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Steps)
        </dd>
    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>
</body>

CookBook/CookBook/Views/Recipe/Edit.cshtml
@model CookBook.Models.Recipe

@{
    ViewBag.Title = "Edit";
}
<body style="background-image:url(http://www.presentationmagazine.com/images3/background-design-orange1024.jpg)">

    <h2>Edit</h2>


    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">0
            <h4 style="font-size:xx-large">Recipe</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.Id)
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.PrepTime, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.PrepTime, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.PrepTime, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.CookTime, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.CookTime, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.CookTime, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.NumberServ, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.NumberServ, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.NumberServ, "", new { @class = "text-danger" })
                </div>
            </div>

<<<<<<< HEAD
            <div class="form-group">
                @Html.LabelFor(model => model.Steps, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Steps, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Steps, "", new { @class = "text-danger" })
                </div>
=======
        <div class="form-group">
            @Html.LabelFor(model => model.Steps, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @** @Html.EditorFor(model => model.Steps, new { htmlAttributes = new { @class = "form-control" } }) *@

                @Html.TextAreaFor(model => model.Steps, new { htmlAttributes = new { @class = "form-control", cols = "1000", rows = "1000", wrap = "virtual" } })


                @Html.ValidationMessageFor(model => model.Steps, "", new { @class = "text-danger" })
>>>>>>> origin/master
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.RecipeType, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.RecipeType, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.RecipeType, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Save" class="btn btn-default" />
                </div>
            </div>
        </div>
    }

    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>

    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
    }
    >
</body>

CookBook/CookBook/Views/Recipe/Index.cshtml
@model IEnumerable<CookBook.Models.Recipe>

    <title></title>
    @{
        ViewBag.Title = "Index";
    }
    
@{
    ViewBag.Title = "Recipes";
}

<h2>Recipes</h2>





<body style="background-image:url(http://www.presentationmagazine.com/images3/background-design-orange1024.jpg)"
     > 


<p style="font-size:x-large">
    @Html.ActionLink("Create New", "Create")
</p>
@using (Html.BeginForm())
{
    <p style="font-size:medium">
        Search by Meal Type: @Html.TextBox("SearchString")
        <input type="submit" value="Search" />
    </p>
}

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            Prep Time (in mins)
        </th>
        <th>
            Cook Time (in mins)
        </th>
        <th>
            People Served
        </th>
        <th>
            Meal Type
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PrepTime)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CookTime)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.NumberServ)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.RecipeType)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id }) |
            @Html.ActionLink("Add Ingredients","Create","RecipeIngredient",new {id=item.Id}, null)
        </td>
    </tr>
}

</table>
    </body>